apps/courses/urls.py
from django.urls import path
from . import views
app_name = 'course'
urlpatterns = [
    path('',views.course_url,name = 'course'),
    path('<int:course_id>/',views.CourseDetail.as_view(),name='detail')
]

my_news/urls.py
from django.contrib import admin
from django.urls import path,include
from my_news import settings
from django.conf.urls.static import static
urlpatterns = [

    path('', include('news.urls')),
    path('user/', include('user.urls')),
    path('',include('verifications.urls')),
    path('doc/',include('doc.urls')),
    path('course/',include('courses.urls')),
    path('admin/',include('admin.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/course/course.html
course.html

{% extends 'base/base.html'%}

{% block link %}
  <link rel="stylesheet" href="../../static/css/course/course.css">

{% endblock %}

{% block title %}在线课堂{% endblock %}

{% block main %}
<main id="course-container">
        <div class="w1200">
            <ul class="course-list">
            {% for one_course in courses %}
                <li class="course-item">

                    <a href="{% url 'course:detail' one_course.id %}">

{#                    <a href="#">#}
                        <img class="course-img" src="{{ one_course.cover_url }}"
                            alt="潭州英语" width="200px" height="200px">
                        <div class="course-content">
                            <p class="course-info">{{ one_course.title }}</p>
                            <p class="course-author">{{ one_course.teacher.name }}{{ one_course.teacher.teacher__positional_title }}</p>
                            <p class="course-price free">免费</p>
                        </div>
                    </a>
                </li>
            {% endfor %}

            </ul>
        </div>
    </main>

{% endblock %}

templates/course/course_detail.html
{% extends 'base/base.html' %}

{% block title %}
    视频页面
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="../../static/css/course/course-detail.css">
{% endblock %}

{% block main %}
<!-- main-contain start  -->
<main id="main">
  <div class="w1200">
    <div class="course-contain">
      <div class="course-top-contain">
        <h4 class="course-title">{{ course.title }}</h4>
        <div class="course-other clearfix">
          <div class="share-list">
            <span>分享至:</span>
            <i class="PyWhich py-weibo"></i>
          </div>
          <div class="buy-list">
            <span class="price">免费</span>
          </div>
        </div>
      </div>
      <div class="course-video" id="course-video">
        <span class="course-data" style="display: none;" data-video-url="{{ course.video_url }}"
              data-cover-url="{{ course.cover_url }}">
        </span>
      </div>

      <div class="course-bottom-contain">
        <div class="course-detail-list">
          <div class="course-item clearfix">
            <h5 class="course-title">{{ course.teacher.name }}</h5>
            <div class="teacher-box clearfix">
              <img src="{{ course.teacher.avatar_url }}"
                   title="Which" class="teacher-avatar">
              <div class="teacher-info">
                <p class="teacher-name">{{ course.teacher.name }}</p>
                <p class="teacher-identify">{{ course.teacher.positional_title }}</p>
              </div>
            </div>
            <div class="item-content">
              {{ course.teacher.profile }}
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">课程简介</h5>
            <div class="item-content">
              {{ course.profile }}
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">课程大纲</h5>
            <div class="item-content">
              <p>{{ course.outline }}</p>
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">帮助中心</h5>
            <div class="item-content">
              <p>1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 </p>
              <p>2. 课程暂不支持下载观看，均为在线观看视频。 </p>
              <p>3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。</p>
              <p>4. 如有问题请咨询客服: 400-1567-315 </p>
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">关于潭州课堂</h5>
            <div class="item-content">
              湖南潭州教育网络科技有限公司拥有千余人的优秀师资团队，是一家师资丰富、教育产品类别众多的在线培训公司。公司总部座落于美丽的星城长沙，2015年9月正式入驻芯城科技园目前拥有近两万平米办公面积。
              在潭州学习的学员已突破1000万人次在线学员覆盖全球，包括中国、加拿大、日本、美国、韩国等诸多国家。
            </div>
          </div>
        </div>
        <div class="course-side">
          <h4 class="side-title">推荐课程</h4>
        </div>
      </div>
    </div>
  </div>
</main>
<!-- main-contain  end -->
{% endblock %}

{% block script %}
    <script src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
    <script src="../../static/js/course/course_detail.js"></script>
{% endblock %}