apps/news/urls.py
from django.urls import path
from . import views
app_name = 'news'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:id>',views.demo),
    path('news/',views.NewsListView.as_view(),name='news_list'),
    path('news/<int:news_id>/', views.News_detail.as_view(), name='news_detail'),
    path('news/banners/',views.BannerView.as_view(),name='banners'),
    path('news/<int:news.id>/comments/',views.CommentView.as_view(),name='comments'),

]

my_news/urls.py
from django.contrib import admin
from django.urls import path,include
from my_news import settings
from django.conf.urls.static import static
urlpatterns = [

    path('', include('news.urls')),
    path('user/', include('user.urls')),
    path('',include('verifications.urls')),
    path('doc/',include('doc.urls')),
    path('course/',include('courses.urls')),
    path('admin/',include('admin.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/news/models.py
from django.db import models
from utils.BaseModel import ModelBase
# Create your models here.

class Tag(ModelBase):
    name  = models.CharField(max_length=64,verbose_name='标签名',help_text='标签名')

    class Meta:
        ordering = ['-update_time','-id']
        db_table = 'tb_tag'
        verbose_name = '新闻标签'

    def __str__(self):
        return self.name


class News(ModelBase):
    title = models.CharField( max_length=150,verbose_name='标题',help_text='标题')
    digest = models.CharField(max_length=200,verbose_name='摘要')
    content = models.TextField(verbose_name='内容')
    clicks = models.IntegerField(default=0, verbose_name='点击量')
    image_url= models.URLField(default="",verbose_name='图片')
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL,null=True) # 允许为空
    author = models.ForeignKey('user.Users',on_delete=models.SET_NULL,null=True)

    class Meta:
        ordering = ['-update_time','-id']
        db_table = 'tb_news'
        verbose_name = '新闻'

    def __str__(self):
        return self.title


class Comments(ModelBase):
    content = models.TextField(verbose_name='内容')
    author = models.ForeignKey('user.Users',on_delete=models.SET_NULL,null=True)
    news = models.ForeignKey('News',on_delete=models.CASCADE)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)

    def to_data(self):
        comments_dict ={
            'news_id':self.news_id,
            'content_id':self.id,
            'content':self.content,
            'author':self.author.username,
            'upsate_time':self.update_time.strftime('%Y年%m月%d日 %H时%M分'),
            'parent':self.parent.to_data() if self.parent else None,
        }
        return comments_dict



    class Meta:
        ordering = ['-update_time','-id']
        db_table = 'tb_comment'
        verbose_name = '评论'

    def __str__(self):
        return '评论{}'.format(self.id)


class HotNews(ModelBase):
    PRI_CHOICES=[
        (1,'第一级'),
        (2,'第二级'),
        (3,'第三级'),
    ]

    news = models.OneToOneField('news',on_delete=models.CASCADE)
    priority = models.IntegerField(choices=PRI_CHOICES,verbose_name='热门新闻优先级')

    class Meta:
        ordering = ['-update_time','-id']
        db_table = 'tb_hot'
        verbose_name = '热门新闻'

    def __str__(self):
        return '热门新闻{}'.format(self.id)


class Banner(ModelBase):
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    ]

    image_url = models.URLField(verbose_name='轮播图url')
    priority = models.IntegerField(choices=PRI_CHOICES,default=6,verbose_name='轮播图优先级')
    news = models.OneToOneField('news',on_delete=models.CASCADE)

    class Meta:
        ordering = ['-update_time','-id']
        db_table = 'tb_banner'
        verbose_name = '轮播图'

    def __str__(self):
        return '轮播图{}'.format(self.id)

apps/news/views.py
from django.db.models import F
from django.shortcuts import render
from django.views import View
from django.core.paginator import Paginator
from . import models
# Create your views here.
from django.http import HttpResponse,HttpResponseNotFound
import logging
logger = logging.getLogger('django')
from utils.res_code import to_json_data,Code,error_map
import json

def index(request):
    tags = models.Tag.objects.only('name','id').filter(is_delete=False)
    hot_news = models.HotNews.objects.select_related('news').only('news__title',
    'news__image_url','news_id').filter(is_delete=False).order_by('priority',
    '-news__click')[0:3]

    # return render(request,'news/index.html',context={
    #     'tags':tags
    # })
    return render(request,'news/index.html',locals())


def demo(request,id):
    res = "<h1 style='color:red'> four in the morning %s </h1> "
    return HttpResponse(res % id)


# 新闻列表
class NewsListView(View):
    def get(self,request):
        """
        tag_id
        page
        route: /news/
        :param request:
        :return:
        http://127.0.0.1:8000/?tag_id=0&page=1
        """
        # 1, 获取前台传的参数， 查询字符串
        try:
            tag_id = int(request.GET.get('tag_id',0 ))
        except Exception as e:
            logger.error('标签错误\n{}'.format(e))
            tag_id=0
        try:
            page = int(request.GET.get('page',1))
        except Exception as e:
            logger.error('页面错误\n{}'.format(e))
            page = 1
        # news_list = models.News.objects.select_related('tag','author').only('id','image_url','title','digest','author__username','tag__name','update_time').filter(is_delete=False)

        # 1- 6
        news_list = models.News.objects.values('id','title','image_url','digest','update_time').annotate(tag_name=F('tag__name'), author=F('author__username'))
        news = news_list.filter(is_delete=False,tag_id=tag_id) or news_list.filter(is_delete=False)
        # 分页
        paginator = Paginator(news,3)
        try:
            news_info = paginator.page(page)
        except Exception as e:
            logger.info('给定的页码错误{}'.format(e))
            news_info = paginator.page(paginator.num_pages)
        # news_info_list = []
        # for n in news_info:
        #     news_info_list.append({
        #         'id':n.id,
        #         'title':n.title,
        #         'digest':n.digest,
        #         'author':n.author.username,
        #         'image_url':n.image_url,
        #         'tag_name':n.tag.name,
        #         'update_time':n.update_time.strftime('%Y年%m月%d日 %H:%M')
        #     })
        data = {
            'news': list(news_info),
            'total_pages':paginator.num_pages
        }
        return to_json_data(data=data)


#新闻详情，传送news_id的值
class News_detail(View):
    def get(self,request,news_id):

        news = models.News.objects.select_related('tag','author').only('title', 'content', 'update_time', 'tag__name', 'author__username').\
            filter(is_delete=False, id=news_id).first()


        comments = models.Comments.objects.select_related('author','parent').only(
            'author__username','update_time','parent__author__username','content'
        ).filter(is_delete=False,news_id=news_id)

        comments_list = []
        for i in comments:
            comments_list.append(
                i.to_data()
            )

        if news:
            return render(request,'news/news_detail.html',context={
                'news':news,
                'comments_list':comments_list,
            })
        else:
            return HttpResponseNotFound('PAGE NOT FOUND')


class BannerView(View):
    def get(self,request):
        # banners = models.Banner.objects.select_related('news').only('image_url',
        # 'news__title','news_id').filter(is_delete=False)[0:6]
        banners = models.Banner.objects.values('image_url').annotate(news_id=F(
        'news_id'),news_title =F('news__title')).filter(is_delete=False)[0:6]


        # banner_info=[]
        # for i in banners:
        #     banner_info.append({
        #         'image_url':i.image_url,
        #         'news_id':i.news_id,
        #         'news_title':i.news.title,
        #     })

        data = {
            'banners':list(banners)

        }
        return to_json_data(data=data)


class CommentView(View):
    def post(self,request,news_id):
        """
        1，判断用户是否登录
        2，获取参数
        3，效验参数
        4，保存到数据库
        :param request:
        :return:
        """
        if request.user.is_authenticated:
            return to_json_data(errno=Code.SESSIONERR,errmsg=error_map[Code.SESSIONERR])

        if models.News.objects.only('id').filter(is_delete=False,id=news_id).exists():
            return to_json_data(errno=Code.PARAMERR,errmsg='新闻不存在')

        #获取参数
        json_str = request.body
        if not json_str:
            return to_json_data(errno=Code.PARAMERR, errmsg='参数错误')

        dict_data = json.loads(json_str)

        #一级评论
        content = dict_data.get('content')
        if not dict_data.get('content'):
            return to_json_data(errno=Code.PARAMERR,errmsg='评论数据不能为空')

        #回复评论
        pt_id = dict_data.get('parent_id')
        try:
            if pt_id:
                if models.Comments.objects.only('id').filter(is_delete=False,id=pt_id,
            news_id=news_id).exists():
                    return to_json_data(errno=Code.PARAMERR,errmsg=error_map[Code.PARAMERR])

        except Exception as e:
            logging.info('前台传的parent_id异常{}'.format(e))
            return to_json_data(errno=Code.PARAMERR,errmsg='未知错误')

        #保存到数据库
        news_content = models.Comments()
        news_content.content=content
        news_content.news_id=news_id
        news_content.author=request.user
        news_content.parent_id=pt_id if pt_id else None
        news_content.save()
        #序列化返回
        return to_json_data(data=news_content.to_data())

templates/news/index.html
{% extends 'base/base.html' %}

{% block title %}
首页面
{% endblock %}

{% block link  %}
     <link rel="stylesheet" href="../../static/css/news/index.css">
{% endblock %}

{% block main-contain %}
   <div class="main-contain">
      <!-- banner start -->
        <div class="banner">
            <ul class="pic">
                <!--淡入淡出banner-->


{#                <li><a href="javascript:void(0);"><img src="../../static/images/ui.png" alt="test"></a></li>#}
{##}
{##}
{#                <li><a href="javascript:void(0);"><img src="../../static/images/youxi.png" alt="test"></a></li>#}
{##}
{##}
{#                <li><a href="javascript:void(0);"><img src="../../static/images/dianshang.png" alt="test"></a></li>#}
{##}
{##}
{#                <li><a href="javascript:void(0);"><img src="../../static/images/zimeiti.png" alt="test"></a></li>#}
{##}
{##}
{#                <li><a href="javascript:void(0);"><img src="../../static/images/python_gui.jpg" alt="test"></a></li>#}
{##}
{##}
{#                <li><a href="javascript:void(0);"><img src="../../static/images/linux.jpg" alt="test"></a></li>#}


            </ul>
            <a href="javascript:void(0);" class="btn prev">
                <i class="PyWhich py-arrow-left"></i></a>
            <a href="javascript:void(0);" class="btn next">
                <i class="PyWhich py-arrow-right"></i></a>
            <ul class="tab">
                <!-- 按钮数量必须和图片一致 -->


{#                <li></li>#}
{##}
{##}
{#                <li></li>#}
{##}
{##}
{#                <li></li>#}
{##}
{##}
{#                <li></li>#}
{##}
{##}
{#                <li></li>#}
{##}
{##}
{#                <li></li>#}


            </ul>
        </div>
      <!-- banner end -->

      <!-- content start -->
      <div class="content">
        <!-- recommend-news start -->
          <ul class="recommend-news">
              {% for i in hot_news %}
              <li>
                  <a href="{% url 'news:news_detail' i.news.id %}" target="_blank">
                      <div class="recommend-thumbnail">
                          <img src="{{ i.news.image_url }}" alt="title">
                      </div>
                      <p class="info">{{ i.news.title }}</p>
                  </a>
              </li>
              {% endfor %}

{#              <li>#}
{#                  <a href="https://www.shiguangkey.com/course/2432" target="_blank">#}
{#                      <div class="recommend-thumbnail">#}
{#                          <img src="../../static/images/python_advanced.jpg" alt="title">#}
{#                      </div>#}
{#                      <p class="info">python高性能编程方法一</p>#}
{#                  </a>#}
{#              </li>#}
{##}
{#              <li>#}
{#                  <a href="https://www.shiguangkey.com/course/2432" target="_blank">#}
{#                      <div class="recommend-thumbnail">#}
{#                          <img src="../../static/images/jichujiaochen.jpeg" alt="title">#}
{#                      </div>#}
{#                      <p class="info">python基础 split 和 join函数比较</p>#}
{#                  </a>#}
{#              </li>#}
          </ul>
        <!-- recommend-news end -->

        <!--  news-nav start-->
          <nav class="news-nav">
              <ul class="clearfix">
                  <li class="active"><a href="javascript:void(0) " data-id="0">最新资讯</a></li>
                    {% for t in tags %}
                  <li><a href="javascript:void(0)" data-id="{{ t.id }}">{{ t.name }}</a>
                  </li>
{##}
{#                  <li><a href="javascript:void(0)" data-id="2">Python基础</a>#}
{#                  </li>#}
{##}
{#                  <li><a href="javascript:void(0)" data-id="3">Python高级</a>#}
{#                  </li>#}
{##}
{#                  <li><a href="javascript:void(0)" data-id="4">Python函数</a>#}
{#                  </li>#}
{##}
{#                  <li><a href="javascript:void(0)" data-id="5">PythonGUI</a>#}
{#                  </li>#}
{##}
{#                  <li><a href="javascript:void(0)" data-id="6">Linux教程</a>#}
{#                  </li>#}
                {% endfor %}
              </ul>
          </nav>
        <!--  news-nav end -->

        <!-- news-contain start -->
          <div class="news-contain">
              <ul class="news-list">
{##}
{#                  <li class="news-item">#}
{#                      <a href="https://www.shiguangkey.com/course/2432" class="news-thumbnail"#}
{#                         target="_blank">#}
{#                          <img src="../../static/images/linux.jpg" alt="linux查找文件或目录命令"#}
{#                               title="linux查找文件或目录命令">#}
{#                      </a>#}
{#                      <div class="news-content">#}
{#                          <h4 class="news-title"><a#}
{#                                  href="#">linux查找文件或目录命令</a>#}
{#                          </h4>#}
{#                          <p class="news-details">linux查找文件或目录命令，前提：知道文件或者目录的具体名字，例如：sphinx.conffind 查找find / -name#}
{#                              dirname 查找目录find -name...</p>#}
{#                          <div class="news-other">#}
{#                              <span class="news-type">Linux教程</span>#}
{#                              <span class="news-time">11/11 18:24</span>#}
{#                              <span class="news-author">python</span>#}
{#                          </div>#}
{#                      </div>#}
{#                  </li>#}
{##}
{#                  <li class="news-item">#}
{#                      <a href="https://www.shiguangkey.com/course/2432" class="news-thumbnail"#}
{#                         target="_blank">#}
{#                          <img src="../../static/images/linux.jpg" alt="linux下svn命令的使用"#}
{#                               title="linux下svn命令的使用">#}
{#                      </a>#}
{#                      <div class="news-content">#}
{#                          <h4 class="news-title"><a#}
{#                                  href="https://www.shiguangkey.com/course/2432/887">linux下svn命令的使用</a>#}
{#                          </h4>#}
{#                          <p class="news-details">1、将文件checkout到本地目录svn checkout path（path是服务器上的目录） 例如：svn checkout#}
{#                              svn://192.168.1.1/pro/domain 简写：svn co2、往版本库中添加新的文件 svn addfile 例如：svn add te...</p>#}
{#                          <div class="news-other">#}
{#                              <span class="news-type">Linux教程</span>#}
{#                              <span class="news-time">11/11 18:24</span>#}
{#                              <span class="news-author">python</span>#}
{#                          </div>#}
{#                      </div>#}
{#                  </li>#}
{##}
{#                  <li class="news-item">#}
{#                      <a href="https://www.shiguangkey.com/course/2432" class="news-thumbnail"#}
{#                         target="_blank">#}
{#                          <img src="../../static/images/linux.jpg" alt="实现linux和windows文件传输"#}
{#                               title="实现linux和windows文件传输">#}
{#                      </a>#}
{#                      <div class="news-content">#}
{#                          <h4 class="news-title"><a#}
{#                                  href="https://www.shiguangkey.com/course/2432/886">实现linux和windows文件传输</a>#}
{#                          </h4>#}
{#                          <p class="news-details">#}
{#                              其实这个题目有点大，这里介绍的只是linux和windows文件传输中的一种，但是这种方法却非常实用，那就是：ZModem协议具体是linux命令是：rz...</p>#}
{#                          <div class="news-other">#}
{#                              <span class="news-type">Linux教程</span>#}
{#                              <span class="news-time">11/11 18:24</span>#}
{#                              <span class="news-author">python</span>#}
{#                          </div>#}
{#                      </div>#}
{#                  </li>#}
{##}
{#                  <li class="news-item">#}
{#                      <a href="https://www.shiguangkey.com/course/2432" class="news-thumbnail"#}
{#                         target="_blank">#}
{#                          <img src="../../static/images/linux.jpg" alt=".htaccess配置详解"#}
{#                               title=".htaccess配置详解">#}
{#                      </a>#}
{#                      <div class="news-content">#}
{#                          <h4 class="news-title"><a#}
{#                                  href="https://www.shiguangkey.com/course/2432">.htaccess配置详解</a>#}
{#                          </h4>#}
{#                          <p class="news-details">　　.htaccess文件设置基础教程 如果你设置好了比如常用的404页面 301重定向 页面还有500页面等会设置了#}
{#                              无非对你的seo技术有很大帮助那么 .htaccess文件到底怎么设置呢　　- .htaccess 文件(或者&quot;分布式...</p>#}
{#                          <div class="news-other">#}
{#                              <span class="news-type">Linux教程</span>#}
{#                              <span class="news-time">11/11 18:24</span>#}
{#                              <span class="news-author">python</span>#}
{#                          </div>#}
{#                      </div>#}
{#                  </li>#}
{##}
{#                  <li class="news-item">#}
{#                      <a href="https://www.shiguangkey.com/course/2432" class="news-thumbnail"#}
{#                         target="_blank">#}
{#                          <img src="../../static/images/linux.jpg" alt="使用nohup命令让linux程序后台运行"#}
{#                               title="使用nohup命令让linux程序后台运行">#}
{#                      </a>#}
{#                      <div class="news-content">#}
{#                          <h4 class="news-title"><a#}
{#                                  href="https://www.shiguangkey.com/course/2432">使用nohup命令让linux程序后台运行</a>#}
{#                          </h4>#}
{#                          <p class="news-details">使用nohup让程序永远后台运行Unix/Linux下一般比如想让某个程序在后台运行，很多都是使用 &amp;#}
{#                              在程序结尾来让程序自动运行。比如我们要运行mysql在后台：/usr/local/mysql/bin/mysqld_safe --user=mysql &amp;但是...</p>#}
{#                          <div class="news-other">#}
{#                              <span class="news-type">Linux教程</span>#}
{#                              <span class="news-time">11/11 18:24</span>#}
{#                              <span class="news-author">python</span>#}
{#                          </div>#}
{#                      </div>#}
{#                  </li>#}

              </ul>
          </div>
        <!-- news-contain end -->

        <!-- btn-more start -->
        <a href="javascript:void(0);" class="btn-more">加载更多</a>
        <!-- btn-more end -->
      </div>
      <!-- content end -->
    </div>
{% endblock %}

{% block script %}
<script src="../../static/js/index.js"></script>
{% endblock %}

templates/news/news_detail.html
{% extends 'base/base.html' %}
{% block title %}文章详情页{% endblock %}
{% block link %}
      <link rel="stylesheet" href="../../static/css/news/news-detail.css">
{% endblock %}

{% block main-contain %}
    <div class="main-contain">

    <div class="news-contain">
      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.update_time }}</span>
          <span class="news-type">{{ news.tag.name }}</span>
        </div>
      </div>
      <article class="news-content">
        {{ news.content | safe}}


      </article>

          <div class="comment-contain">
        <div class="comment-pub clearfix">
          <div class="new-comment">
            文章评论(<span class="comment-count">0</span>)
          </div>
          {% if user.is_authenticated %}
          <div class="comment-control logged-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请填写评论">
            <button class="comment-btn">发表评论</button>
          </div>
        {% else %}
          <div class="comment-control please-login-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请登录后参加评论" readonly>
            <button class="comment-btn">发表评论</button>
          </div>
        {% endif %}

        </div>
        <ul class="comment-list">
          {% for one_comment in comments_list %}
            <li class="comment-item">
            <div class="comment-info clearfix">
              <img src="../../static/images/avatar.jpeg" alt="avatar" class="comment-avatar">
              <span class="comment-user">{{ one_comment.author }}</span>
              <!--<span class="comment-pub-time">{{ one_comment.update_time }}</span>-->
            </div>
            <div class="comment-content">{{ one_comment.content }}</div>

              {% if one_comment.parent %}
              <div class="parent_comment_text">
                <div class="parent_username">{{ one_comment.parent.author }}</div>
                <br/>
                <div class="parent_content_text">
                  {{ one_comment.parent.content }}
                </div>
              </div>
              {% endif %}

              <div class="comment_time left_float">{{ one_comment.update_time }}</div>
              <a href="javascript:void(0);" class="reply_a_tag right_float">回复</a>
              <form class="reply_form left_float" comment-id="{{ one_comment.content_id }}"
                    news-id="{{ one_comment.news_id }}">
                <textarea class="reply_input"></textarea>
                <input type="button" value="回复" class="reply_btn right_float">
                <input type="reset" name="" value="取消" class="reply_cancel right_float">
              </form>
          </li>
          {% endfor %}

        </ul>
      </div>

    </div>
</div>

{% endblock %}

{% block script %}
    <script src="../../ static/js/news/news_detail.js"></script>
{% endblock %}