apps/doc/urls.py
from django.urls import path
from . import views
app_name = 'doc'
urlpatterns = [
    path('',views.doc,name='docs'),
    path('download/<int:doc_id>/', views.DocDownload.as_view(), name='download'),


]

my_news/urls.py
from django.contrib import admin
from django.urls import path,include
from my_news import settings
from django.conf.urls.static import static
urlpatterns = [

    path('', include('news.urls')),
    path('user/', include('user.urls')),
    path('',include('verifications.urls')),
    path('doc/',include('doc.urls')),
    path('course/',include('courses.urls')),
    path('admin/',include('admin.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/doc/models.py
from django.db import models
from utils.BaseModel import ModelBase
# Create your models here.


class Doc(ModelBase):
    file_url = models.URLField(verbose_name='文件url',help_text='文件url')
    title = models.CharField(max_length=200,verbose_name='文档标题')
    desc = models.TextField(verbose_name='文档描述')
    image_url= models.URLField(default='',verbose_name='图片url')
    author = models.ForeignKey('user.Users',on_delete=models.SET_NULL,null=True)

    class Meta:
        db_table='tb_doc'
        verbose_name='文档'


    def __str__(self):
        return self.title

apps/doc/views.py
import requests
from . import models

from django.shortcuts import render
from django.http import FileResponse, Http404
from django.utils.encoding import escape_uri_path
from django.views import View
from my_news import settings




def doc(request):
    """
    """
    docs = models.Doc.objects.defer('author', 'create_time', 'update_time', 'is_delete').filter(is_delete=False)
    return render(request, 'doc/docDownload.html',context={
        'docs':docs
    })


class DocDownload(View):

    def get(self, request, doc_id):
        doc_file = models.Doc.objects.only('file_url').filter(is_delete=False, id=doc_id).first()
        if doc_file:
            doc_file_url = doc_file.file_url  #media/流畅的python.pdf
            doc_url = settings.DOC_DOWNLOAD_URL + doc_file_url
            res = FileResponse(requests.get(doc_url))

            #获取后缀
            ex_name = doc_url.split('.')[-1] #获取ptf

            if not ex_name:
                raise Http404('文件名异常')
            else:
                ex_name = ex_name.lower()

            if ex_name == "pdf":
                res["Content-type"] = "application/pdf"
            elif ex_name == "zip":
                res["Content-type"] = "application/zip"
            elif ex_name == "doc":
                res["Content-type"] = "application/msword"
            elif ex_name == "xls":
                res["Content-type"] = "application/vnd.ms-excel"
            elif ex_name == "docx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            elif ex_name == "ppt":
                res["Content-type"] = "application/vnd.ms-powerpoint"
            elif ex_name == "pptx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

            else:
                raise Http404("文档格式不正确！")

            doc_filename = escape_uri_path(doc_url.split('/')[-1])
            # 设置为inline，会直接打开
            res["Content-Disposition"] = "attachment; filename*=UTF-8''{}".format(doc_filename)
            return res

        else:
            raise Http404("文档不存在！")

templates/doc/docDownload.html
{% extends 'base/base.html' %}
{% block title %}文档下载{% endblock %}
{% block link %}
      <link rel="stylesheet" href="../../static/css/doc/docDownload.css">

{% endblock %}

{% block main-contain %}

<div class="main-contain ">
    <div class="banner">
      <img src="/media/doc_banner_2.jpg"
           alt="">
    </div>
    <div class="pay-doc-contain">
      <ul class="pay-list">

        {% for doc in docs %}

          <li class="pay-item">
{#          <div class="pay-img doc"></div>#}
            <img src="{{ doc.image_url }}" class="pay-img doc"/>
          <div class="d-contain">
            <p class="doc-title">{{ doc.title }}</p>
            <p class="doc-desc">{{ doc.desc }}</p>

            <a href="{% url 'doc:download' doc.id %}" class="pay-price">下载</a>
          </div>
        </li>

        {% endfor %}

      </ul>
    </div>
  </div>

{% endblock %}